lukso-network/tools-lsp-factory

.eslintrc.json
.github/workflows/lint-build-test.yml
.github/workflows/node.js.yml
.github/workflows/publish.yml
.gitmodules
.npmignore
README.md
package-lock.json
package.json
src/lib/classes/lsp3-universal-profile.ts
src/lib/helpers/erc725.ts
test/lsp3-factory.test.ts
tsconfig.json

- **What is the current behavior?**
Nothing happens 🤦 
- **What is the new behavior (if this is a feature change)?**
Github Release will trigger an `npm publish --access public` to the `npm` registry. 🚀

NPM Publish Workflow

---

src/lib/helpers/config.helper.spec.ts
src/lib/helpers/config.helper.ts
src/lib/helpers/deployment.helper.ts

**Bug fix** 
Use the correct keys...

fix(config-helper): use the correct keys

---

.github/workflows/lint-build-test.yml
CHANGELOG.md
package-lock.json
package.json

chore(release): 1.0.2-alpha.7

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 1.0.2-alpha.8

---

package.json

fix npm publish, versions.json was missing in package

fix: npm publish add .json file

---

src/lib/services/lsp3-account.service.ts
src/versions.json

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- **What is the current behavior?** (You can also link to an open issue here)
- **What is the new behavior (if this is a feature change)?**
- **Other information**:

fix: setData tx

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 1.1.2

---

README.md
docs/digital-assets.md

- Updates Readme.md with up to date usage guide and adds Digital Asset docs

docs: improve docs

---

src/lib/classes/lsp3-universal-profile.ts

code clean
console.log
remove console.log

chore: remove log

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 1.1.3

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 1.1.4

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 1.1.5

---

src/lib/classes/lsp3-universal-profile.ts
src/lib/helpers/config.helper.ts
src/lib/helpers/deployment.helper.ts
src/lib/services/digital-asset.service.ts
src/lib/services/lsp3-account.service.ts
src/lib/services/universal-receiver.service.ts

improvement
Makes Gas cost dynamic by estimating gas before execution.

Estimate gas cost

---

package-lock.json
package.json
src/lib/classes/digital-asset.ts
src/lib/services/base-contract.service.ts
src/lib/services/digital-asset.service.ts
src/versions.json

fix
currently deployed digital asset contracts are not implementations. 
Now deploys mintable digital asset contracts with external mint function

fix: deploy mintable digital assets

---

src/lib/classes/digital-asset.ts
src/lib/classes/lsp3-universal-profile.ts
src/lib/helpers/deployment.helper.ts
src/lib/services/key-manager.service.ts
src/lib/services/lsp3-account.service.ts
src/lib/services/universal-receiver.service.ts

Docs
Adds JSDocs for external LSP3UniversalProfile and DigitalAsset functions

docs: add jsdocs for digital asset and UniversalProfile classes

---

docs/deployment/universal-profile.md
docs/introduction/getting-started.md

Docs
Updates Documentation to be in line with recent changes to docs repo

docs: sync with update to docs repo

---

.github/workflows/publish.yml
package.json
src/lib/classes/digital-asset.ts
src/lib/classes/lsp3-universal-profile.ts
src/lib/interfaces/deployment-events.ts
src/lib/interfaces/lsp3-profile.ts
src/lib/lsp-factory.ts
typedoc.json

Docs
Auto generate + publish techinical reference docs to github pages on release
Some technical reference examples added

docs: generate tech ref docs on release

---

docs/classes/DigitalAsset.md
docs/classes/LSP3UniversalProfile.md

Docs
Improved md docs for class methods

docs: improve class methods docs

---

docs/classes/LSP3UniversalProfile.md

Docs
Syncs tech ref docs with LUKSO docs website

docs: sync LSP3UniversalProfile spec docs

---

docs/classes/LSP3UniversalProfile.md

Docs
Syncs docs changes with LSPFactory section in https://github.com/lukso-network/docs

docs: sync with docs website

---

src/lib/classes/lsp3-universal-profile.spec.ts
src/lib/classes/lsp3-universal-profile.ts
src/lib/helpers/config.helper.ts
src/lib/helpers/uploader.helper.spec.ts
src/lib/helpers/uploader.helper.ts
src/lib/interfaces/lsp-factory-options.ts
src/lib/interfaces/profile-deployment.ts
src/lib/interfaces/profile-upload-options.ts
src/lib/lsp-factory.ts
src/lib/services/lsp3-account.service.ts

Allow custom IPFS options to be passed in uploadOptions object

feature: add custom uploadOptions param

---

docs/classes/lsp3-universal-profile.md
docs/classes/lsp4-digital-asset-metadata.md
docs/classes/lsp7-digital-asset.md
docs/classes/lsp8-identifiable-digital-asset.md
package-lock.json
package.json
src/lib/classes/lsp3-universal-profile.spec.ts
src/lib/classes/lsp3-universal-profile.ts
src/lib/classes/lsp4-digital-asset-metadata.ts
src/lib/classes/lsp7-digital-asset.ts
src/lib/classes/lsp7-digtal-asset.spec.ts
src/lib/classes/lsp8-identifiable-digital-asset.ts
src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
src/lib/classes/proxy-deployer.ts
src/lib/helpers/config.helper.ts
src/lib/helpers/erc725.helper.ts
src/lib/helpers/uploader.helper.spec.ts
src/lib/helpers/uploader.helper.ts
src/lib/interfaces/digital-asset-deployment.ts
src/lib/interfaces/index.ts
src/lib/interfaces/lsp3-profile.ts
src/lib/interfaces/lsp4-digital-asset.ts
src/lib/interfaces/metadata.ts
src/lib/lsp-factory.ts
src/lib/services/base-contract.service.ts
src/lib/services/digital-asset.service.ts
src/lib/services/lsp3-account.service.ts
src/lib/services/universal-receiver.service.ts
test/lsp4-digital-asset.mock.ts
test/test.utils.ts

Adds LSP4 metadata class and upload functions

Digital asset metadata

---

docs/classes/lsp3-universal-profile.md
docs/classes/lsp4-digital-asset-metadata.md
docs/classes/lsp7-digital-asset.md

Updates documentation for metadata upload options

docs: update uploadOptions object

---

docs/introduction/reactive-deployment.md

Docs
Documentation reflected legacy deployReactive functions
Updates to reflect new deployReactive flag in ContractDeploymentOptions

docs: update deploy reactive documentation

---

docs/classes/lsp3-universal-profile.md
docs/classes/lsp4-digital-asset-metadata.md
docs/classes/lsp7-digital-asset.md
docs/deployment/contract-deployment-options.md
docs/deployment/fungible-token.md
docs/deployment/nft.md

Minor changes to documentation

docs: minor improvements to docs

---

docs/classes/lsp3-universal-profile.md

Fix broken link on LSP3UniversalProfile page

docs: fix broken link on lsp3 class page

---

README.md
docs/classes/lsp3-universal-profile.md
docs/deployment/universal-profile.md

Docs
Improves docs for LSP3 metadata

docs: improve LSP3 metadata upload docs

---

docs/deployment/universal-profile.md

docs: fix typo in LSP3 docs

---

docs/classes/lsp3-universal-profile.md
docs/classes/lsp4-digital-asset-metadata.md
docs/classes/lsp7-digital-asset.md
docs/classes/lsp8-identifiable-digital-asset.md
docs/deployment/contract-deployment-options.md
docs/deployment/fungible-token.md
docs/deployment/nft.md
docs/deployment/reactive-deployment.md
docs/deployment/universal-profile.md
docs/getting-started.md

This PR implements the changes proposed in  [PR166 of the docs](https://github.com/lukso-network/docs/pull/166/)
it includes:
- overall grammar and styling improvement
- removing HTML
Already implemented Callum's suggestions from PR166

grammar and styling for docs

---

docs/deployment/universal-profile.md

This PR updates the links of the `tools/lspfactory.js` sub-folder.
The structure will be changed with [PR181](https://github.com/lukso-network/docs/pull/181/files).
Please merge this PR **BEFORE** PR181 is merged. Otherwise, the tool's sub-folders will be overwritten with the old file system in this repo, causing the build to fail.

Resolving Links for Docs 

---

docs/classes/lsp3-universal-profile.md
docs/classes/lsp7-digital-asset.md
docs/classes/lsp8-identifiable-digital-asset.md
docs/deployment/digital-asset.md
docs/deployment/universal-profile.md
docs/getting-started.md
src/lib/helpers/config.helper.ts
src/lib/helpers/deployment.helper.ts
src/lib/helpers/uploader.helper.spec.ts
src/lib/helpers/uploader.helper.ts

Docs
Improves documentation for deploy reactive events with new structure

docs: improve deploy reactive events documentation

---

tsconfig.json

Enable full sourcemap instead of inline sourcemap

improvement: enable sourcemap, disable inline sourcemap

---

docs/classes/lsp3-universal-profile.md
docs/classes/lsp7-digital-asset.md
docs/classes/lsp8-identifiable-digital-asset.md
docs/getting-started.md

Adds error handling into reactive deployment examples

docs: add error handling into reactive deployment examples

---

CHANGELOG.md
README.md
package-lock.json
package.json

Release v2.3.0

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.3.1

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.3.2

---

CHANGELOG.md
package-lock.json
package.json
src/lib/helpers/deployment.helper.ts
src/lib/services/digital-asset.service.ts
src/lib/services/universal-profile.service.ts

chore: release v2.3.2

---

README.md
docs/getting-started.md

Update getting started doc and README to use l16 RPC and chainId

docs: update docs to use l16 RPC and chainId

---

src/lib/interfaces/deployment-events.ts
src/lib/lsp-factory.ts

Improvement
Gets chainId from ethereum provider if passed

improvement: get chainId from provider

---

docs/classes/universal-profile.md
docs/deployment/universal-profile.md
docs/getting-started.md
src/lib/classes/universal-profile.ts

Looks like the docs were outdated

docs: controllingAccounts -> controllerAddresses

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.3.3

---

src/lib/helpers/uploader.helper.ts

Fixes issue where height and width are swapped for image uploads

chore: fix reversed image sizes

---

src/lib/services/universal-profile.service.ts

Improvement
SETDATA -> SUPER_SETDATA

improvement: Give URD super setdata permission for UP

---

CHANGELOG.md
package-lock.json
package.json

chore(release): 2.3.4

---

CHANGELOG.md
package-lock.json
package.json

Version bump for 2.4.0 
* Upgrade lsp-smart-contracts to v0.7.0 (#163)
* Upgrade lsp-smart-contracts to v0.7.0 ([#163](https://github.com/lukso-network/tools-lsp-factory/issues/163)) ([761cd81](https://github.com/lukso-network/tools-lsp-factory/commit/761cd81089c55e4ab15d2a6c234ca39e40f3e46a))

chore(release): 2.4.0

---

docs/classes/universal-profile.md

Fixes broken link in docs after docs structure update

docs: fix broken link

---

docs/deployment/digital-asset.md

https://github.com/lukso-network/docs/pull/427

docs: fix typo in code snippet

---

docs/deployment/options.md

Minor fix in options documentation. Change LSP1UniversalProfile -> LSP1UniversalReceiverDelegate

docs: fix LSP1UniversalProfile options

---

CHANGELOG.md
package-lock.json
package.json

Update main branch to sync documentation

chore: sync main

---

docs/classes/lsp7-digital-asset.md
docs/classes/lsp8-identifiable-digital-asset.md
docs/classes/universal-profile.md

We had a couple of broken links

docs: fix docs links

---

docs/deployment/universal-profile.md

fix documentation (replace uploadMetaData. by uploadProfileData)
https://github.com/lukso-network/docs/issues/341

replace uploadMetaData by uploadProfileData

---

package-lock.json
package.json
src/versions.json

feat: upgrade lsp to v0.11.1

---

src/lib/helpers/config.helper.ts

fix: use default SC version

---

docs/classes/lsp7-digital-asset.md
docs/classes/lsp8-identifiable-digital-asset.md
docs/deployment/digital-asset.md
docs/deployment/universal-profile.md

Update outdated links.
Spotted in:
https://github.com/lukso-network/docs/pull/703

docs: update links

---

README.md

Mainly used to trigger a new release because the previous one failed because of environment.

fix: readme title
