- CHANGELOG.md
- package-lock.json
- package.json
v1.1.0 was already published in npm in `2021-08-30T12:22:02.169Z` so publishing v1.1.1
> chore(release): 1.1.1

- docs/constructing-lsp3-data.md
- docs/getting-started.md
- docs/reactive-deployment.md
- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/helpers/deployment.helper.spec.ts
- src/lib/helpers/deployment.helper.ts
- src/lib/interfaces/profile-deployment.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/lsp3-account.service.ts
- src/lib/services/universal-receiver.service.ts
- src/versions.json
- test/deployment-events.mock.ts
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- renames LSP3Account contracts ERC725Account to reflect contract upgrade
- **What is the current behavior?** (You can also link to an open issue here)
UP contract is referred to as LSP3Account
- **What is the new behavior (if this is a feature change)?**
UP contract is referred to ERC725Account
- **Other information**:
> chrore(contract): rename lsp3Account to erc725Account

- README.md
docs update
When using the code example from the README to deploy a Universal Profile, several errors occur:
- syntax error due to extra curly brace at the end.
- incorrect property name to obtain UP address
- cannot deploy because missing keccak256 checksum of profile + background images
All the errors in the deployment code snippet mentioned above are fixed.
Anyone can now copy-paste the code snippet from the README to deploy + create a UP easily ✅
> docs: correct + improve deployment code snippet in README

- src/lib/classes/lsp3-universal-profile.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/key-manager.service.ts
- src/versions.json
Improvement
KeyManager contracts are deployed as full contracts
Uses Proxy/base contract pattern to deploy KeyManager
> chore: add KeyManager base/proxy deployment

- src/lib/services/lsp3-account.service.ts
Bug Fix.
When deploying a Universal Profile with the lsp-factory, the key `AddressPermissions[]` (number of addresses that have a permission set on the UP) is set to `0x02`. ❌ 
This makes [erc725.js](https://github.com/ERC725Alliance/erc725.js) to not work when trying to fetch all the array elements.
[LSP2 - ERC725Y JSON Schema](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#example) defines that for any ERC725Y key of type Array, the length value should be stored as a `uint256`, left zero padded.
So fix this bug by setting the array length to `0x0000000000000000000000000000000000000000000000000000000000000002` ✅
> fix: add zero-left padding for `AddressPermissions[]` length

- package-lock.json
- package.json
Dependency update
lsp-factory.js uses an old beta version of [erc725.js](https://github.com/ERC725Alliance/erc725.js)
Upgrade erc725.js dependency to version 0.9.0
Closes #62
> chore: update erc725.js to v0.9.0

- docs/deployment/contract-deployment-options.md
- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp7-digtal-asset.spec.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/lsp3-account.service.spec.ts
- test/test.utils.ts
Feature
Enable deploying contracts with custom provided bytecode.
Requirement for now is to deploy full contract if custom bytecode is passed without proxy deployment. In future we may want to allow passing custom bytecode to be deployed as the base contract
> feature: allow passing custom bytecode

- docs/classes/lsp7-digital-asset.md
- docs/classes/lsp8-identifiable-digital-asset.md
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp7-digtal-asset.spec.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
- src/lib/helpers/config.helper.spec.ts
- src/lib/helpers/config.helper.ts
- src/lib/interfaces/digital-asset-deployment.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/lsp3-account.service.ts
Feature
Adds LSP4Creators key for creators[] value passed in digital asset options
> chore: set LSP4Creators[] when deploying digital assets

- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/key-manager.service.ts
- src/lib/services/lsp3-account.service.ts
- src/lib/services/universal-receiver.service.ts
- src/versions.json
- test/test.utils.ts
improvement
Deploys a new Universal Receiver Delegate contract for every UP deployment
Reuse the default URD contract for all UPS
User can specify a custom URD address, or if a URD contract should be deployed by using 'deployProxy' key.
> chore: reuse URD address between UPs

- src/lib/classes/proxy-deployer.ts
- src/lib/helpers/config.helper.ts
- src/versions.json
Imrpovemenet
Uses wrong version names
Add version 0.5.0  as default contract versions
> chore: update contract versions to 0.5.0

- .github/workflows/publish.yml
CI
Removes autogenerated docs from CI, this is legacy behaviour
> ci: remove autogenerated docs from CI

- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp7-digtal-asset.spec.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
- src/lib/interfaces/digital-asset-deployment.ts
- src/lib/interfaces/profile-deployment.ts
improvement
Return type of `deploy` methods are not inferred based on the `deployReactive` parameter. This means developers need to cast types to avoid errors.
Return type is conditionally determined based on the `deployReactive` parameter. if `deployReactive: true` return type is Observable, if `deployReactive: false` or omitted return type is Promise
> chore: improve return typing for deploy methods

- docs/classes/lsp7-digital-asset.md
- docs/classes/lsp8-identifiable-digital-asset.md
fix
Updates documentation. `controllerAddress` param for LSP7/LSP8 was using old `ownerAddress`
> docs: update lsp7/8 controllerAddress param

- docs/getting-started.md
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/interfaces/deployment-events.ts
- src/lib/lsp-factory.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/key-manager.service.ts
- src/lib/services/lsp3-account.service.ts
Feature
Allows passing the window ethereum object as the provider on instantiation. This will then try and create a web3provider object to use as the signer for transactions to trigger browser extensions (e.g MetaMask) to confirm transactions
> feat: allow passing window.ethereum object during instantiation

- package-lock.json
- package.json
- src/lib/helpers/uploader.helper.spec.ts
- src/lib/helpers/uploader.helper.ts
- src/lib/services/digital-asset.service.ts
Fix
Removes Jimp and image-size libraries used to resize images from Array buffers in Node environment. These packages cause compilation errors when using lsp-factory in the browser. 
**Breaking change**: depricates uploading images from buffer
> chore!: remove jjmp and imge-size

- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/classes/lsp4-digital-asset-metadata.ts
- src/lib/classes/lsp7-digtal-asset.spec.ts
- src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
- src/lib/helpers/erc725.helper.ts
- src/lib/helpers/uploader.helper.ts
- src/lib/interfaces/digital-asset-deployment.ts
- src/lib/interfaces/lsp3-profile.ts
- src/lib/interfaces/lsp4-digital-asset.ts
- src/lib/interfaces/profile-deployment.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/lsp3-account.service.ts
- test/lsp3-profile.mock.ts
- test/lsp4-digital-asset.mock.ts
Feature
Pass metadata as an object as accepted by `encodeData` function of erc725.js. Bypasses upload and will go straight to erc725js for encoding
> feat: allow passing metadata formatted for erc725.js

- docs/classes/lsp7-digital-asset.md
- docs/deployment/contract-deployment-options.md
- docs/deployment/universal-profile.md
- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp7-digtal-asset.spec.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
- src/lib/helpers/deployment.helper.ts
- src/lib/interfaces/digital-asset-deployment.ts
- src/lib/interfaces/profile-deployment.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/lsp3-account.service.ts
- test/test.utils.ts
Improvement
Currently contract deployment options accept `byteCode`, `version` and `libAddress` as separate config params.
This PR refactors this config object so now `version` will provide the function for all 3 possibilities. This stops the question of e.g. _"what happens if I pass a lib address with custom bytecode"_. Only `byteCode`, `version` OR `libAddress` can now be passed.
No changes to internal logic. A configuration object using the old config schema is created from the new deployment options structure to be passed to internal deployment code. 
**This is a breaking change to the configuration object for all  `deploy` methods.**
> improvement: deployment config version parameter

- docs/classes/lsp3-universal-profile.md
- docs/classes/lsp4-digital-asset-metadata.md
- docs/classes/lsp7-digital-asset.md
- docs/classes/lsp8-identifiable-digital-asset.md
- docs/deployment/digital-asset.md
- docs/deployment/universal-profile.md
- docs/getting-started.md
- src/index.ts
- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/classes/lsp4-digital-asset-metadata.ts
- src/lib/classes/lsp7-digtal-asset.spec.ts
- src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
- src/lib/helpers/config.helper.ts
- src/lib/helpers/uploader.helper.spec.ts
- src/lib/helpers/uploader.helper.ts
- src/lib/interfaces/digital-asset-deployment.ts
- src/lib/interfaces/lsp-factory-options.ts
- src/lib/interfaces/profile-deployment.ts
- src/lib/interfaces/profile-upload-options.ts
- src/lib/lsp-factory.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/lsp3-account.service.ts
Flattens `uploadOptions` parameters to just `ipfsGateway`
Before:
```javascript
await lspFactory.LSP7DigitalAsset.deploy({...}, {
uploadOptions: {
ipfsClientOptions: {
host: 'ipfs.infura.io',
port: 5001,
protocol: 'https',
}
}
});
```
After: 
```javascript
await lspFactory.LSP7DigitalAsset.deploy({...}, {
ipfsGateway: {
host: 'ipfs.infura.io',
port: 5001,
protocol: 'https',
}
});
```
ipfsGateway can also be passed as a string:
```javascript
await lspFactory.LSP7DigitalAsset.deploy({...}, {
ipfsGateway: "https://ipfs.infura.io:5001"
});
```
```javascript
await lspFactory.LSP7DigitalAsset.deploy({...}, {
ipfsGateway: "https://ipfs.infura.io"
});
```
If no port is provided, port will be set to 5001
See example at https://docs.lukso.tech/tools/lsp-factoryjs/deployment/universal-profile#ipfs-up …
> chore!: Flatten upload options object

- docs/classes/lsp3-universal-profile.md
- docs/classes/lsp4-digital-asset-metadata.md
- docs/classes/lsp7-digital-asset.md
- docs/classes/lsp8-identifiable-digital-asset.md
- docs/deployment/universal-profile.md
Improves function parameter specification pages in class pages. 
- Links to more specifics descriptions on Deployment pages
- Removes optional `?` syntax in favour of `[, options]` or `(optional)` highlighting
Before: 
After:
> docs: improve class spec docs

- src/lib/classes/lsp3-universal-profile.ts
- src/lib/helpers/config.helper.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/lsp3-account.service.spec.ts
- src/lib/services/lsp3-account.service.ts
Improvement
Batches `setData` and `transferOwnership` transactions together for digital assets and universal profile deployment. 
No longer waits for `setData` transaction to be mined before sending `transferOwnership`.
sending `transferOwnership` transaction does wait for `setData` to be sent, so nonces are in the correct order to avoid permission errors
> improvement: batch setData and transferOwnership transactions

- docs/classes/lsp3-universal-profile.md
- docs/classes/lsp7-digital-asset.md
- docs/classes/lsp8-identifiable-digital-asset.md
- docs/deployment/digital-asset.md
- docs/deployment/options.md
- docs/deployment/universal-profile.md
- docs/getting-started.md
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp7-digtal-asset.spec.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digtal-asset.spec.ts
- src/lib/interfaces/contract-options.ts
- src/lib/interfaces/digital-asset-deployment.ts
- src/lib/interfaces/profile-deployment.ts
- src/lib/services/digital-asset.service.ts
Changes Digital Asset options object to use same structure as Universal Profile options for generic contract options
Uses full contract names as keys (LSP7DigitalAsset, LSP8IdentifiabledigitalAsset)
Before
```js
lspFactory.LSP7DigitalAsset.deploy(
{ ... },
{
version: '0.5.0',
deployProxy: true,
ipfsGateway: '...',
}
);
```
After:
```js
lspFactory.LSP7DigitalAsset.deploy(
{ ... },
{
LSP7DigitalAsset: {
version: '0.5.0',
deployProxy: true,
},
ipfsGateway: '...',
}
);
```
> improvement!: Add generic contract options object to digital asset options

- docs/classes/lsp3-universal-profile.md
- docs/deployment/digital-asset.md
- docs/deployment/options.md
- docs/deployment/universal-profile.md
- src/lib/classes/lsp3-universal-profile.spec.ts
- src/lib/classes/lsp3-universal-profile.ts
- src/lib/classes/lsp7-digital-asset.ts
- src/lib/classes/lsp8-identifiable-digital-asset.ts
- src/lib/helpers/deployment.helper.spec.ts
- src/lib/helpers/deployment.helper.ts
- src/lib/interfaces/profile-deployment.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/key-manager.service.ts
- src/lib/services/lsp3-account.service.ts
- src/lib/services/universal-receiver.service.ts
- test/test.utils.ts
Renames Universal Profile contract names to use full LSP names. 
ERC725Account -> LSP0ERC725Account
KeyManager -> LSP6KeyManager
UniversalReceiverDelegate -> LSP1UniversalReceiverDelegate
e.g.
```js
lspFactory.UniversalProfile.deploy({...}, {
LSP0ERC725Account: {...}, // Can also be passed as ERC725Account
LSP6KeyManager: {...},
LSP1UniversalReceiverDelegate: {...}
});
```
returns 
```js
{
LSP0ERC725Account: {
address: '...',
receipt: {
...
}
},
LSP1UniversalReceiverDelegate: {
address: '...',
receipt: {
...
}
},
LSP6KeyManager: {
address: '...',
receipt: {
...
}
}
}
```
Please merge https://github.com/lukso-network/tools-lsp-factory/pull/117 first
> improvement!: rename universal profile contracts

- docs/deployment/universal-profile.md
- src/lib/classes/universal-profile.ts
- src/lib/interfaces/lsp3-profile.ts
Adds Avatar to LSP3 Metadata.
Avatars are passed as an Array, where each element can be a File object or a metadata object according to LSP2.
```javascript
<input type="file" id="avatar">
<script>
const myLocalAvatar = document.getElementById('avatar').files[0];
const myUniversalProfileData = {
name: 'My Universal Profile',
description: 'My cool Universal Profile',
asset: [
myLocalAvatar,
{
hashFunction: 'keccak256(bytes)',
hash: '0x5f3dbd89cde4dde36241c501203b67a93b89908063f5516535136bc25f712e11',
url: 'ipfs://QmWkAki4mLq2c9hsbKs4HFCaZdpUX1jLKKBb5y8YMATkak',
fileType: 'image/obj',
},
]
};
await lspFactory.UniversalProfile.deploy({
controllingAccounts: ['0x...'],
lsp3Profile: myUniversalProfileData
});
<script/>
```
Updates Docs
> feat: add avatar to LSP3 upload

- src/lib/helpers/config.helper.ts
- src/versions.json
Feature
Currently the base contracts default address are only specified for L14.
Require the new base contract addresses for L16.
> chore: add base contract addresses on L16 network

- src/lib/helpers/deployment.helper.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/universal-profile.service.ts
Fix
Removes gas price when estimating gas. When passing gas price in the RPC call to eth node the request does not go through, the applies to the geth version used on l16 but not l14
> fix: remove gas price from gas estimates

- docs/classes/lsp7-digital-asset.md
- docs/classes/lsp8-identifiable-digital-asset.md
- docs/classes/universal-profile.md
Docs update
removes old observable return type from class spec files
> docs: remove old observale return type from docs

- src/lib/classes/universal-profile.spec.ts
Remove custom ipfs gatway tests from integration tests.
Infura removed their public gateway so we can no longer use this in these tests. 
Custom ipfs gateway is already tested in upload-helper.spec.ts so we can remove these tests
> fix: Remove custom ipfs gatway from integration tests

- src/versions.json
- As discussed, the base contracts used for deploying are not verified and we don't have the ability to verify them as they were optimized with an unknown optimizer run. Thats why we included contracts that are deployed and optimized using the default config in the lsp-smart-contract repo.
Contract deployed using lsp-factory are not verified on block explorer.
Contract deployed using lsp-factory will be verified on block explorer.
Contract addresses to be reviewed.
> chore: use verified 0.6.1 lsp-contracts for l16

- package-lock.json
- package.json
- src/lib/classes/proxy-deployer.ts
- src/lib/helpers/config.helper.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/digital-asset.service.ts
- src/versions.json
Upgrades lsp-smart-contracts to v0.7.0
Pending: 
[] Upgrade erc725.js to enable ENCRYPT permissions
[] Add 0.7.0 base contract addresses into versions.json
> feat!: Upgrade lsp-smart-contracts to v0.7.0

- CHANGELOG.md
- docs/classes/lsp7-digital-asset.md
- docs/classes/lsp8-identifiable-digital-asset.md
- docs/classes/universal-profile.md
- package-lock.json
- package.json
- src/lib/classes/proxy-deployer.ts
- src/lib/helpers/config.helper.ts
- src/lib/services/base-contract.service.ts
- src/lib/services/digital-asset.service.ts
- src/lib/services/universal-profile.service.ts
- src/versions.json
Releases v2.4.0
I have manually verified the bytecode for the new base contracts in the `versions.json`
* Upgrade lsp-smart-contracts to v0.7.0 (#163)
* Upgrade lsp-smart-contracts to v0.7.0 ([#163](https://github.com/lukso-network/tools-lsp-factory/issues/163)) ([761cd81](https://github.com/lukso-network/tools-lsp-factory/commit/761cd81089c55e4ab15d2a6c234ca39e40f3e46a))
* Give URD super setdata permission for UP ([3a291bf](https://github.com/lukso-network/tools-lsp-factory/commit/3a291bf06b29c3f2382f52b439d89b172b643a38))
* add missing type for instance uploadMetadata ([3a291bf](https://github.com/lukso-network/tools-lsp-factory/commit/75ef1a6c994eabf4fa34fd3a101f8557fb2057c4))
* swap height and width when uploading images ([a14e0fd](https://github.com/lukso-network/tools-lsp-factory/com …
> chore: release v2.4.0

- src/lib/interfaces/index.ts
- src/lib/interfaces/lsp3-profile.ts
- src/lib/interfaces/lsp4-digital-asset.ts
- src/lib/interfaces/metadata.ts
Fixes typo in `LinkMetadata` interface.
> fix: typo in `LinkMetadata` interface

- src/lib/services/universal-profile.service.ts
The LSP1Delegate is not given the permission `REENTRANCY` on the UP being deployed.
Fixed this by adding the missing permission when setting the permissions.
> fix: give permission `REENTRANCY` to LSP1Delegate

- CHANGELOG.md
- package-lock.json
- package.json
- Adjust versions of lsp-smart-contracts and erc725.js to match latest. ([c6b04a6](https://github.com/lukso-network/tools-lsp-factory/commit/c6b04a6f27d0aa59bf6d9a910054ec758546031c))
- get deployed contract addresses from event logs ([e674f69](https://github.com/lukso-network/tools-lsp-factory/commit/e674f693549d8eaa4b0ecbb39f9bf9424c291e50))
- give permission `REENTRANCY` to LSP1Delegate ([edb0c5e](https://github.com/lukso-network/tools-lsp-factory/commit/edb0c5e665ee22e95a79de6fe429423bd792f693))
> chore(release): 2.5.1

- .github/workflows/release.yml
- RELEASE.md
CI
Current release CI is broken and requires manually editing CHANGELOG
1. Merge develop into main.
2. Release Please will create the release PR going to main.
3. Merge the generated release PR.
4. Package will be published to NPM.
the first time a new release is run the CHANGELOG will still need to be manually updated, this is because the way the previous CI did things broke the CHANGELOG for the _next_ release. After this the CHANGELOG should be running correctly again
> ci: add release please workflow

- .npmignore
- package.json
- tsconfig.json
- tsconfig.module.json
This PR introduce source map.
When on a dapp an issue comes from the lsp-factory library, it s not possible to have a look at the typescript file of the library.
We can access the typescript file of the library from the browser of the dapp.
It was a real concern for me that activating inline source map increases the weight of the library 
(From 990kB to 1.2 MB) as we want our library to be as light as possible.
On this topic Andrea said that
"There is currently really no other way. Normally the consumer of the library should just be able to work with the source code if we had a real language".
> Fix source map

- README.md
- docs/getting-started.md
- src/lib/helpers/config.helper.ts
**docs update**
The `main` branch still shows the docs with `l16` instead of `testnet`. This is incorrectly fetched in by the auto bot in the docs.lukso.tech PR
> Update main branch with latest docs

- src/versions.json
"UniversalProfileInit": 0x3024D38EA2434BA6635003Dc1BDC0daB5882ED4F 
"LSP6KeyManagerInit" : 0x2Fe3AeD98684E7351aD2D408A43cE09a738BF8a4 
"LSP7MintableInit": 0x28B7CcdaD1E15cCbDf380c439Cc1F2EBe7f5B2d8 
"LSP8MintableInit": 0xd787a2f6B14d4dcC2fb897f40b87f2Ff63a07997 
"LSP1UniversalReceiverDelegateUP": 0x7870C5B8BC9572A8001C3f96f7ff59961B23500D
> fix: add v14 base contracts for mainnet
